// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require('mongoose');

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema({
  'actors': [String],
  'countries': [String],
  'director': String,
  'genres': [String],
  'imdb': {
    id: String,
    rating: Number,
    votes: Number,
  },
  'metacritic': Number,
  'plot': String,
  'poster': String,
  'rated': String,
  'runtime': Number,
  'title': String,
  'writers': [String],
  'year': Number,
}, {
  timestamps: true,
});

module.exports = mongoose.model('movies', schema, 'movies');
